language: python

python:
  - 2.6
  - 3.3

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - pip install -q --use-mirrors Cython numpy
  # For Python 2.6 we also need argparse
  - pip install argparse
  - pip install coverage
  - pip install coveralls
  - python -V

script:
  - python runtests.py -g -m full --coverage

after_success:
    - coveralls
