# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false

env:
  global:
    # Use non-interactive backend
    - MPLBACKEND: Agg
    - CYTHON_TRACE: 1

matrix:
  include:
    - python: 2.7
      env:
        - PYFLAKES=1
        - PEP8=1
        - NUMPYSPEC=numpy
      before_install:
        - pip install pep8==1.5.1
        - pip install pyflakes
      script:
        - PYFLAKES_NODOCTEST=1 pyflakes pywt demo | grep -E -v 'unable to detect undefined names|assigned to but never used|imported but unused|redefinition of unused' > test.out; cat test.out; test \! -s test.out
        - pep8 pywt demo

    - python: 3.5
      env:
        - NUMPYSPEC=numpy
    - python: 3.4
      env:
        - NUMPYSPEC=numpy
    - python: 2.6
      env:
        - NUMPYSPEC="numpy==1.7.2"
    - python: 2.7
      env:
        - NUMPYSPEC="numpy==1.9.1"

cache: pip

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
  - pip install --upgrade pip
  - pip install --upgrade wheel
  # Set numpy version first, other packages link against it
  - pip install $NUMPYSPEC
  - pip install Cython matplotlib nose coverage codecov
  - set -o pipefail

script:
  # Define a fixed build dir so next step works
  - python setup.py build --build-lib build/lib/
  - nosetests build/lib/ --tests pywt/tests

after_success:
  - codecov
