# After changing this file, check it on:
#   http://lint.travis-ci.org/
language: python
sudo: false

env:
  global:
    # Use non-interactive backend
    - MPLBACKEND: Agg
    - CYTHON_TRACE: 1

matrix:
  include:
    - python: 2.7
      env:
        - PYFLAKES=1
        - PEP8=1
        - NUMPYSPEC=numpy
        - MPLSPEC=matplotlib
      before_install:
        - pip install pep8==1.5.1
        - pip install pyflakes
      script:
        - PYFLAKES_NODOCTEST=1 pyflakes pywt demo | grep -E -v 'unable to detect undefined names|assigned to but never used|imported but unused|redefinition of unused' > test.out; cat test.out; test \! -s test.out
        - pep8 pywt demo
    - python: 3.5
      env:
        - NUMPYSPEC=numpy
        - MPLSPEC=matplotlib
        - USE_WHEEL=1
    - os: linux
      python: 3.4
      env:
        - NUMPYSPEC=numpy
        - MPLSPEC=matplotlib
        - USE_SDIST=1
    - os: linux
      python: 2.6
      env:
        - NUMPYSPEC="numpy==1.9.3"
        - MPLSPEC="matplotlib<2"
    - python: 2.7
      env:
        - NUMPYSPEC=numpy
        - MPLSPEC=matplotlib
    - python: 3.5
      env:
        - NUMPYSPEC=numpy
        - MPLSPEC=matplotlib
        - REFGUIDE_CHECK=1  # run doctests only

cache: pip

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - python -V
  - pip install --upgrade pip
  - pip install --upgrade wheel
  # Set numpy version first, other packages link against it
  - pip install $NUMPYSPEC
  - pip install Cython $MPLSPEC nose coverage codecov futures
  - set -o pipefail
  - if [ "${USE_WHEEL}" == "1" ]; then pip install wheel; fi
  - |
    if [ "${REFGUIDE_CHECK}" == "1" ]; then
        pip install sphinx numpydoc
    fi

script:
  # Define a fixed build dir so next step works
  - |
    if [ "${USE_WHEEL}" == "1" ]; then
        # Need verbose output or TravisCI will terminate after 10 minutes
        pip wheel . -v
        pip install PyWavelets*.whl -v
        pushd demo
        nosetests pywt
        popd
    elif [ "${USE_SDIST}" == "1" ]; then
        python setup.py sdist
        # Move out of source directory to avoid finding local pywt
        pushd dist
        pip install PyWavelets* -v
        nosetests pywt
        popd
    elif [ "${REFGUIDE_CHECK}" == "1" ]; then
        pip install -e . -v
        python util/refguide_check.py --doctests
    else
        CFLAGS="--coverage" python setup.py build --build-lib build/lib/ --build-temp build/tmp/
        nosetests build/lib/ --tests pywt/tests
    fi

after_success:
  - codecov
  # Travis CI has old gcov, needs object dir explicitly specified
  - gcov --object-directory build/tmp/pywt/_extensions/c/ build/tmp/pywt/_extensions/c/*.o
  - bash <(curl -s https://codecov.io/bash)
