# AppVeyor.com is a Continuous Integration service to build and run tests under
# Windows
# https://ci.appveyor.com/project/PyWavelets/pywt

# This file is built on the template here:
# http://python-packaging-user-guide.readthedocs.org/en/latest/appveyor/

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"

build: off

install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip wheel numpy Cython nose
    --wheel-dir c:\\tmp\\wheels
    --find-links c:\\tmp\\wheels
    --download-cache=c:\\tmp\\downloads"
  - "%PYTHON%\\python.exe -m pip install numpy Cython nose
    --find-links c:\\tmp\\wheels --no-index"

test_script:
  - "util/appveyor/build.cmd %PYTHON%\\python.exe setup.py test"

after_test:
  - "util/appveyor/build.cmd %PYTHON%\\python.exe setup.py bdist_wheel"

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: dist\*

cache:
  - "c:\\tmp\\wheels -> appveyor.yml"
  - "c:\\tmp\\downloads -> appveyor.yml"
